// Generated by CoffeeScript 1.8.0
(function() {
  var express, getParsedFactData, router;

  express = require('express');

  getParsedFactData = require('./helpers').getParsedFactData;

  router = express.Router();

  router.get(/\/facts/, function(req, res) {
    var conceptName, identifier;
    identifier = req.query.identifier;
    conceptName = req.query.conceptName;
    return getParsedFactData(identifier, conceptName, function(data) {
      return res.end(JSON.stringify(data));
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=facts.js.map
