// Generated by CoffeeScript 1.8.0
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('index', {
      pageData: {
        facts: null,
        sets: [],
        series: {},
        friendlyNames: {}
      }
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
