// Generated by CoffeeScript 1.8.0
(function() {
  var JSONStream, ObjectStringTransformStream, express, http, request, router, sendResponse, tickerResolver;

  express = require('express');

  http = require('http');

  request = require('request');

  JSONStream = require('JSONStream');

  tickerResolver = require('./helpers').tickerResolver;

  ObjectStringTransformStream = require('../streams/ObjectStringTransformStream').ObjectStringTransformStream;

  sendResponse = function(identifier, elementName, res) {
    return request({
      url: "https://0741ae13-4f99-4ffb-8282-60d27e161c7f-bluemix.cloudant.com/facts/_design/factsMainViews/_view/EntityConceptName?key=[\"http://www.sec.gov/CIK/" + identifier + "\",\"" + elementName + "\"]&include_docs=true&stale=update_after&reduce=false"
    }).pipe(JSONStream.parse('rows.*.doc')).pipe(new ObjectStringTransformStream()).pipe(res);
  };

  router = express.Router();

  router.get(/\/rawfacts\/([a-zA-Z0-9]+)\/(.+)/, function(req, res) {
    var cik, cikOrTicker, elementName;
    cikOrTicker = req.params[0];
    elementName = req.params[1];
    cik = null;
    if (cikOrTicker.match(/[0-9]{10}/)) {
      return sendResponse(cikOrTicker, elementName, res);
    } else {
      return tickerResolver(cikOrTicker, function(identifier) {
        if (identifier == null) {
          return res.end('[]');
        } else {
          return sendResponse(identifier.cik, elementName, res);
        }
      });
    }
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=rawfacts.js.map
