// Generated by CoffeeScript 1.9.2
(function() {
  var express, getCloudantUrl, request, router, uuid;

  request = require('request');

  express = require('express');

  uuid = require('node-uuid');

  getCloudantUrl = require('./helpers').getCloudantUrl;

  router = express.Router();

  router.post('/save', function(req, res) {
    var options;
    if ((req.body.sets == null) && (req.body.series == null)) {
      res.send(500);
    }
    uuid = uuid.v4();
    return options = {
      uri: (getCloudantUrl()) + "/share/",
      method: 'POST',
      json: {
        sets: req.body.sets,
        series: req.body.series,
        uuid: uuid
      },
      headers: {
        'Content-type': 'application/json'
      }
    };
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=save.js.map
