// Generated by CoffeeScript 1.9.2
(function() {
  var JSONStream, express, getCloudantUrl, request, router;

  express = require('express');

  JSONStream = require('JSONStream');

  request = require('request');

  getCloudantUrl = require('./helpers').getCloudantUrl;

  router = express.Router();

  router.get('/size', function(req, res) {
    var cloudantUri;
    cloudantUri = (getCloudantUrl()) + "/factsdev/_design/factsMainViews/_view/EntityConceptName?stale=update_after";
    return request({
      url: cloudantUri
    }).pipe(JSONStream.parse('rows.*.value')).on('data', function(data) {
      return res.end(JSON.stringify(data));
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=size.js.map
