// Generated by CoffeeScript 1.8.0
(function() {
  var JSONStream, express, request, router;

  express = require('express');

  JSONStream = require('JSONStream');

  request = require('request');

  router = express.Router();

  router.get('/size', function(req, res) {
    var cloudantUri;
    cloudantUri = "https://0741ae13-4f99-4ffb-8282-60d27e161c7f-bluemix.cloudant.com/facts/_design/factsMainViews/_view/EntityConceptName?stale=update_after";
    return request({
      url: cloudantUri
    }).pipe(JSONStream.parse('rows.*.value')).on('data', function(data) {
      return res.end(JSON.stringify(data));
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=size.js.map
