// Generated by CoffeeScript 1.9.2
(function() {
  var express, router;

  module.exports = router;

  express = require('express');

  router = express.Router();

  router.get('/statements', function(req, res) {
    return res.render('statements');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=statements.js.map
