// Generated by CoffeeScript 1.9.2
(function() {
  var FACTransformStream, JSONStream, express, getCloudantUrl, http, request, router, tickerResolver;

  express = require('express');

  http = require('http');

  request = require('request');

  JSONStream = require('JSONStream');

  tickerResolver = require('./helpers').tickerResolver;

  getCloudantUrl = require('./helpers').getCloudantUrl;

  FACTransformStream = require('../streams/FACTransformStream').FACTransformStream;

  router = express.Router();

  router.post('/statementData', function(req, res) {
    var entity, reqEntities;
    if (req.body.entities == null) {
      res.send(500);
    }
    reqEntities = ((function() {
      var i, len, ref, results;
      ref = req.body.entities;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        entity = ref[i];
        results.push("\"" + entity + "\"");
      }
      return results;
    })()).join();
    return request({
      url: (getCloudantUrl()) + "/factsdev/_design/factsMainViews/_view/FACEntity?keys=[" + reqEntities + "]&include_docs=true&stale=update_after"
    }).pipe(JSONStream.parse('rows.*.doc')).pipe(new FACTransformStream(req.body.entities)).on('data', function(data) {
      data['entities'] = ['INTERNATIONAL BUSINESS MACHINES CORP', 'MICROSOFT CORP'];
      return res.end(JSON.stringify(data));
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=statementData.js.map
