// Generated by CoffeeScript 1.9.2
(function() {
  var stream,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  stream = require('stream');

  exports.BookmarkExtractorStream = (function(superClass) {
    extend(BookmarkExtractorStream, superClass);

    function BookmarkExtractorStream(bookmark) {
      this.bookmark = bookmark;
      this.buffer = "";
      this.found = false;
      BookmarkExtractorStream.__super__.constructor.apply(this, arguments);
    }

    BookmarkExtractorStream.prototype._transform = function(chunk, enc, next) {
      var match;
      if (!this.found) {
        this.buffer += chunk.toString('utf8');
        match = this.buffer.match(/\"bookmark\"\:\"([^\"]+)\"/);
        if (match != null) {
          this.bookmark.value = match[1];
          this.buffer = null;
        }
      }
      this.push(chunk);
      return next();
    };

    return BookmarkExtractorStream;

  })(stream.Transform);

}).call(this);

//# sourceMappingURL=BookmarkExtractorStream.js.map
