// Generated by CoffeeScript 1.9.2
(function() {
  var Fact, stream,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  stream = require('stream');

  Fact = require('../model/Fact').Fact;

  exports.CsvHeaderStream = (function(superClass) {
    extend(CsvHeaderStream, superClass);

    function CsvHeaderStream() {
      this.dimensions = {};
      CsvHeaderStream.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    CsvHeaderStream.prototype._transform = function(chunk, enc, next) {
      var k, ref, v;
      ref = new Fact(chunk).GetDimensions();
      for (k in ref) {
        v = ref[k];
        this.dimensions[k] = true;
      }
      return next();
    };

    CsvHeaderStream.prototype._flush = function(next) {
      var k, v;
      this.push((function() {
        var ref, results;
        ref = this.dimensions;
        results = [];
        for (k in ref) {
          v = ref[k];
          results.push(k);
        }
        return results;
      }).call(this));
      return next();
    };

    return CsvHeaderStream;

  })(stream.Transform);

}).call(this);

//# sourceMappingURL=CsvHeaderStream.js.map
