// Generated by CoffeeScript 1.9.2
(function() {
  var Fact, stream,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Fact = require('../model/Fact').Fact;

  stream = require('stream');

  exports.FACTransformStream = (function(superClass) {
    extend(FACTransformStream, superClass);

    function FACTransformStream() {
      this.bsFacts = {
        Assets: {},
        CurrentAssets: {},
        NoncurrentAssets: {},
        LiabilitiesAndEquity: {},
        Liabilities: {},
        CurrentLiabilities: {},
        NoncurrentLiabilities: {},
        CommitmentsAndContingencies: {},
        TemporaryEquity: {},
        RedeemableNoncontrollingInterest: {},
        Equity: {},
        EquityAttributableToNoncontrollingInterest: {},
        EquityAttributableToParent: {}
      };
      this.bsDates = {};
      FACTransformStream.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    FACTransformStream.prototype._transform = function(chunk, enc, next) {
      var fact, timeIndex;
      fact = new Fact(chunk);
      timeIndex = "" + (fact.EndDate.getTime());
      switch (fact.ElementName) {
        case 'fac:Assets':
          this.bsFacts.Assets[timeIndex] = fact.Value;
          break;
        case 'fac:CurrentAssets':
          this.bsFacts.CurrentAssets[timeIndex] = fact.Value;
          break;
        case 'fac:NoncurrentAssets':
          this.bsFacts.NoncurrentAssets[timeIndex] = fact.Value;
          break;
        case 'fac:LiabilitiesAndEquity':
          this.bsFacts.LiabilitiesAndEquity[timeIndex] = fact.Value;
          break;
        case 'fac:Liabilities':
          this.bsFacts.Liabilities[timeIndex] = fact.Value;
          break;
        case 'fac:CurrentLiabilities':
          this.bsFacts.CurrentLiabilities[timeIndex] = fact.Value;
          break;
        case 'fac:NoncurrentLiabilities':
          this.bsFacts.NoncurrentLiabilities[timeIndex] = fact.Value;
          break;
        case 'fac:CommitmentsAndContingencies':
          this.bsFacts.CommitmentsAndContingencies[timeIndex] = fact.Value;
          break;
        case 'fac:TemporaryEquity':
          this.bsFacts.TemporaryEquity[timeIndex] = fact.Value;
          break;
        case 'fac:RedeemableNoncontrollingInterest':
          this.bsFacts.RedeemableNoncontrollingInterest[timeIndex] = fact.Value;
          break;
        case 'fac:Equity':
          this.bsFacts.Equity[timeIndex] = fact.Value;
          break;
        case 'fac:EquityAttributableToNoncontrollingInterest':
          this.bsFacts.EquityAttributableToNoncontrollingInterest[timeIndex] = fact.Value;
          break;
        case 'fac:EquityAttributableToParent':
          this.bsFacts.EquityAttributableToParent[timeIndex] = fact.Value;
      }
      this.bsDates["" + (fact.EndDate.getTime())] = fact.EndDate.getTime();
      return next();
    };

    FACTransformStream.prototype._flush = function(next) {
      var date, i, k, len, outputBsDates, outputBsFacts, sortedBsDates, timeIndex, v, value;
      outputBsFacts = {};
      sortedBsDates = (function() {
        var ref, results;
        ref = this.bsDates;
        results = [];
        for (k in ref) {
          v = ref[k];
          results.push(new Date(v));
        }
        return results;
      }).call(this);
      sortedBsDates.sort(function(a, b) {
        if (a > b) {
          return -1;
        } else if (a < b) {
          return 1;
        } else {
          return 0;
        }
      });
      outputBsDates = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = sortedBsDates.length; i < len; i++) {
          value = sortedBsDates[i];
          results.push(value.getMonth() + 1 + "/" + value.getDate() + "/" + value.getFullYear());
        }
        return results;
      })();
      outputBsFacts = {
        Assets: [],
        CurrentAssets: [],
        NoncurrentAssets: [],
        LiabilitiesAndEquity: [],
        Liabilities: [],
        CurrentLiabilities: [],
        NoncurrentLiabilities: [],
        CommitmentsAndContingencies: [],
        TemporaryEquity: [],
        RedeemableNoncontrollingInterest: [],
        Equity: [],
        EquityAttributableToNoncontrollingInterest: [],
        EquityAttributableToParent: []
      };
      for (i = 0, len = sortedBsDates.length; i < len; i++) {
        date = sortedBsDates[i];
        timeIndex = "" + (date.getTime());
        outputBsFacts.Assets.push(this.bsFacts.Assets[timeIndex] != null ? this.bsFacts.Assets[timeIndex] : '&nbsp;');
        outputBsFacts.CurrentAssets.push(this.bsFacts.CurrentAssets[timeIndex] != null ? this.bsFacts.CurrentAssets[timeIndex] : '&nbsp;');
        outputBsFacts.NoncurrentAssets.push(this.bsFacts.NoncurrentAssets[timeIndex] != null ? this.bsFacts.NoncurrentAssets[timeIndex] : '&nbsp;');
        outputBsFacts.LiabilitiesAndEquity.push(this.bsFacts.LiabilitiesAndEquity[timeIndex] != null ? this.bsFacts.LiabilitiesAndEquity[timeIndex] : '&nbsp;');
        outputBsFacts.Liabilities.push(this.bsFacts.Liabilities[timeIndex] != null ? this.bsFacts.Liabilities[timeIndex] : '&nbsp;');
        outputBsFacts.CurrentLiabilities.push(this.bsFacts.CurrentLiabilities[timeIndex] != null ? this.bsFacts.CurrentLiabilities[timeIndex] : '&nbsp;');
        outputBsFacts.NoncurrentLiabilities.push(this.bsFacts.NoncurrentLiabilities[timeIndex] != null ? this.bsFacts.NoncurrentLiabilities[timeIndex] : '&nbsp;');
        outputBsFacts.CommitmentsAndContingencies.push(this.bsFacts.CommitmentsAndContingencies[timeIndex] != null ? this.bsFacts.CommitmentsAndContingencies[timeIndex] : '&nbsp;');
        outputBsFacts.TemporaryEquity.push(this.bsFacts.TemporaryEquity[timeIndex] != null ? this.bsFacts.TemporaryEquity[timeIndex] : '&nbsp;');
        outputBsFacts.RedeemableNoncontrollingInterest.push(this.bsFacts.RedeemableNoncontrollingInterest[timeIndex] != null ? this.bsFacts.RedeemableNoncontrollingInterest[timeIndex] : '&nbsp;');
        outputBsFacts.Equity.push(this.bsFacts.Equity[timeIndex] != null ? this.bsFacts.Equity[timeIndex] : '&nbsp;');
        outputBsFacts.EquityAttributableToNoncontrollingInterest.push(this.bsFacts.EquityAttributableToNoncontrollingInterest[timeIndex] != null ? this.bsFacts.EquityAttributableToNoncontrollingInterest[timeIndex] : '&nbsp;');
        outputBsFacts.EquityAttributableToParent.push(this.bsFacts.EquityAttributableToParent[timeIndex] != null ? this.bsFacts.EquityAttributableToParent[timeIndex] : '&nbsp;');
      }
      this.push({
        bsDates: outputBsDates,
        bsFacts: outputBsFacts
      });
      return next();
    };

    return FACTransformStream;

  })(stream.Transform);

}).call(this);

//# sourceMappingURL=FACTransformStream.js.map
