// Generated by CoffeeScript 1.9.2
(function() {
  var Fact, stream,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Fact = require('../model/Fact').Fact;

  stream = require('stream');

  exports.FactTransformStream = (function(superClass) {
    extend(FactTransformStream, superClass);

    function FactTransformStream() {
      this.facts = [];
      FactTransformStream.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    FactTransformStream.prototype._transform = function(chunk, enc, next) {
      var fact, hashValue;
      fact = new Fact(chunk.doc);
      if (fact.IsDuration && fact.GetPeriodDescription() === 'other' || fact.IsNil) {
        return next();
      }
      hashValue = fact.GetHashValue();
      if (!this.facts[hashValue]) {
        this.facts[hashValue] = fact;
      } else if (this.facts[hashValue].FilingDate < fact.FilingDate) {
        this.facts[hashValue] = fact;
      } else if (this.facts[hashValue].FilingDate === fact.FilingDate && !this.facts[hashValue].Amendment && fact.Amendment) {
        this.facts[hashValue] = fact;
      }
      return next();
    };

    FactTransformStream.prototype._flush = function(next) {
      var fact, facts, hash, i, len, ref, seriesCollection, seriesCollectionParsed, seriesDescription;
      seriesCollection = {};
      ref = this.facts;
      for (hash in ref) {
        fact = ref[hash];
        seriesDescription = fact.GetSeriesDescription();
        if (seriesCollection[seriesDescription] == null) {
          seriesCollection[seriesDescription] = [];
        }
        seriesCollection[seriesDescription].push(fact);
      }
      seriesCollectionParsed = {};
      for (seriesDescription in seriesCollection) {
        facts = seriesCollection[seriesDescription];
        facts.sort(function(a, b) {
          return a.GetSortValue(b);
        });
        for (i = 0, len = facts.length; i < len; i++) {
          fact = facts[i];
          if (fact.Value == null) {
            continue;
          }
          if (seriesCollectionParsed[seriesDescription] == null) {
            seriesCollectionParsed[seriesDescription] = {
              data: [],
              renderingData: {}
            };
          }
          seriesCollectionParsed[seriesDescription].data.push([fact.EndDate.getTime(), fact.Value]);
          seriesCollectionParsed[seriesDescription].renderingData[(fact.EndDate.getTime()) + "--" + fact.Value] = {
            rendering: "https://www.sec.gov/cgi-bin/viewer?action=view&cik=" + fact.CIK + "&accession_number=" + fact.AccesssionNumber,
            xml: decodeURIComponent(fact.URL),
            unit: fact.GetUnitDescription()
          };
        }
        seriesCollectionParsed[seriesDescription].shareKey = facts[0].GetSeriesKey();
      }
      this.push(seriesCollectionParsed);
      return next();
    };

    return FactTransformStream;

  })(stream.Transform);

}).call(this);

//# sourceMappingURL=FactTransformStream.js.map
