// Generated by CoffeeScript 1.8.0
(function() {
  var stream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  stream = require('stream');

  exports.ObjectStringTransformStream = (function(_super) {
    __extends(ObjectStringTransformStream, _super);

    function ObjectStringTransformStream() {
      this.first = true;
      ObjectStringTransformStream.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    ObjectStringTransformStream.prototype._transform = function(chunk, enc, next) {
      if (this.first) {
        this.push('[');
        this.first = false;
      } else {
        this.push(',\n');
      }
      this.push(JSON.stringify(chunk));
      return next();
    };

    ObjectStringTransformStream.prototype._flush = function(next) {
      if (this.first) {
        this.push('[]');
      } else {
        this.push(']');
      }
      return next();
    };

    return ObjectStringTransformStream;

  })(stream.Transform);

}).call(this);

//# sourceMappingURL=ObjectStringTransformStream.js.map
