// Generated by CoffeeScript 1.9.2
(function() {
  var stream,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  stream = require('stream');

  exports.UniqueArrayWriteStream = (function(superClass) {
    extend(UniqueArrayWriteStream, superClass);

    function UniqueArrayWriteStream(myArray, keySelector, valueSelector, limit) {
      this.myArray = myArray;
      this.keySelector = keySelector;
      this.valueSelector = valueSelector;
      this.limit = limit;
      UniqueArrayWriteStream.__super__.constructor.call(this, {
        objectMode: true
      });
    }

    UniqueArrayWriteStream.prototype._write = function(chunk, enc, next) {
      if (Object.keys(this.myArray).length < this.limit) {
        this.myArray[chunk[this.keySelector]] = chunk[this.valueSelector];
      }
      return next();
    };

    return UniqueArrayWriteStream;

  })(stream.Writable);

}).call(this);

//# sourceMappingURL=UniqueArrayWriteStream.js.map
